  # Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Another Engineering Blog
email: will.hennessey735@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://anotherengineeringblog.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sicklickwill
github_username:  WillHennessey

# Build settings

#theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
timezone: Europe/Dublin
#markdown:         redcarpet
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
gems: [jekyll-paginate, jekyll-feed]
paginate: 5
paginate_path: "page:num"
tagline:          'A Jekyll theme'

author:
  name:           'Will Hennessey'
  url:            https://twitter.com/sicklickwill

version: 0.0.1